In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('loan_approved.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
df.sample(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
508,LP002626,Male,Yes,0,Graduate,Yes,2479,3013.0,188.0,360.0,1.0,Urban,Y
243,LP001807,Male,Yes,2,Graduate,Yes,6250,1300.0,108.0,360.0,1.0,Rural,Y
32,LP001097,Male,No,1,Graduate,Yes,4692,0.0,106.0,360.0,1.0,Rural,N
504,LP002619,Male,Yes,0,Not Graduate,No,3814,1483.0,124.0,300.0,1.0,Semiurban,Y
33,LP001098,Male,Yes,0,Graduate,No,3500,1667.0,114.0,360.0,1.0,Semiurban,Y

In [41]:
# how to check the null value
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [7]:
df['Gender'].mode()

0    Male
Name: Gender, dtype: object

In [9]:
df.loc[df['Gender'].isnull(),'Gender']='Male'

In [11]:
df['Married'].mode()

0    Yes
Name: Married, dtype: object

In [18]:
df.loc[df['Married'].isnull(),'Married']='Married'

In [22]:
df['Dependents'].dtype

dtype('O')

In [23]:
df['Dependents'].mode()

0    0
Name: Dependents, dtype: object

In [24]:
df.loc[df['Dependents'].isnull(),'Dependents']='0'

In [26]:
df['Self_Employed'].mode()

0    No
Name: Self_Employed, dtype: object

In [27]:
df.loc[df['Self_Employed'].isnull(),'Self_Employed']='No'

In [29]:
df['LoanAmount'].describe()

count    592.000000
mean     146.412162
std       85.587325
min        9.000000
25%      100.000000
50%      128.000000
75%      168.000000
max      700.000000
Name: LoanAmount, dtype: float64

In [32]:
df['LoanAmount'].median()

128.0

In [33]:
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=128

In [35]:
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=df['LoanAmount'].median()

In [36]:
df.loc[df['Loan_Amount_Term'].isnull(),'Loan_Amount_Term']=df['Loan_Amount_Term'].median()

In [39]:
df['Credit_History'].describe()

count    564.000000
mean       0.842199
std        0.364878
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Credit_History, dtype: float64

In [40]:
df.loc[df['Credit_History'].isnull(),'Credit_History']=df['Credit_History'].mean()